export const  SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const  SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const  SIGN_IN_FAIL = "SIGN_IN_FAIL";

export const USER_SIGNOUT = "USER_SIGNOUT"


export const  GET_ALL_POLICIES_REQUEST = "GET_ALL_POLICIES_REQUEST";
export const  GET_ALL_POLICIES_SUCCESS = "GET_ALL_POLICIES_SUCCESS";
export const  GET_ALL_POLICIES_FAIL = "GET_ALL_POLICIES_FAIL";

export const  GET_POLICY_BY_PAN_REQUEST = "GET_POLICY_BY_PAN_REQUEST";
export const  GET_POLICY_BY_PAN_SUCCESS = "GET_POLICY_BY_PAN_SUCCESS";
export const  GET_POLICY_BY_PAN_FAIL = "GET_POLICY_BY_PAN_FAIL";

export const  ADD_POLICY_REQUEST = "ADD_POLICY_REQUEST";

export const  ADD_POLICY_SUCCESS = "ADD_POLICY_SUCCESS";

export const  ADD_POLICY_FAIL = "ADD_POLICY_FAIL";